// Package wire provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package wire

import (
	"time"
)

// Defines values for HealthStatus.
const (
	Ok HealthStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// Defines values for MessageRole.
const (
	Kiln MessageRole = "kiln"
	User MessageRole = "user"
)

// Valid indicates whether the value is a known member of the MessageRole enum.
func (e MessageRole) Valid() bool {
	switch e {
	case Kiln:
		return true
	case User:
		return true
	default:
		return false
	}
}

// Defines values for TicketState.
const (
	Blocked TicketState = "blocked"
	Done    TicketState = "done"
	Ready   TicketState = "ready"
	Shaping TicketState = "shaping"
	Working TicketState = "working"
)

// Valid indicates whether the value is a known member of the TicketState enum.
func (e TicketState) Valid() bool {
	switch e {
	case Blocked:
		return true
	case Done:
		return true
	case Ready:
		return true
	case Shaping:
		return true
	case Working:
		return true
	default:
		return false
	}
}

// Board GetBoard's full snapshot (03 §4), grouped in render order — the `board` SSE event payload and GET /api/board's response body are the identical shape (04 D7): absolute, never a delta, so a reconnect's resync is just "render the next board event" (07 §7–§8). `ready` is in exact pull order, top-to-bottom, so the user sees what gets pulled next (03 §5, 07 §7).
type Board struct {
	Blocked []Ticket `json:"blocked"`
	Done    []Ticket `json:"done"`
	Ready   []Ticket `json:"ready"`
	Shaping []Ticket `json:"shaping"`

	// WorkerFree Free (non-busy) worker slots — the capacity chip (07 §7).
	WorkerFree int `json:"worker_free"`

	// WorkerTotal Total worker capacity slots (03 §2.3).
	WorkerTotal int      `json:"worker_total"`
	Working     []Ticket `json:"working"`
}

// Health defines model for Health.
type Health struct {
	Status  HealthStatus `json:"status"`
	Version string       `json:"version"`
}

// HealthStatus defines model for Health.Status.
type HealthStatus string

// Message One persisted transcript row (07 §3), as returned oldest-first by GET /api/messages.
type Message struct {
	MessageId int64       `json:"message_id"`
	Role      MessageRole `json:"role"`
	Text      string      `json:"text"`
	Timestamp time.Time   `json:"timestamp"`
}

// MessageRole defines model for Message.Role.
type MessageRole string

// MessagePostResponse POST /api/message's 202 body (07 §4) — both ids the client needs to reconcile its optimistic send.
type MessagePostResponse struct {
	EventId   int64 `json:"event_id"`
	MessageId int64 `json:"message_id"`
}

// MessageRequest POST /api/message body (07 §4). Text only in v1; 09 adds STT in front of this seam.
type MessageRequest struct {
	Text string `json:"text"`
}

// SayEvent The `say` SSE event payload (07 §4) — one event per brain say (renamed from `speak`, 07 A1). message_id matches the corresponding Message row from GET /api/messages/the transcript.
type SayEvent struct {
	At        time.Time `json:"at"`
	MessageId int64     `json:"message_id"`
	Text      string    `json:"text"`
}

// Ticket One ticket as rendered on the board (03 §2.2). Column/zone placement is derived from `state`, never carried as a separate field (03 D1).
type Ticket struct {
	// BlockedReason Set iff state is blocked (03 I4); full text, shown on the card (07 §7).
	BlockedReason *string   `json:"blocked_reason,omitempty"`
	Body          string    `json:"body"`
	CreatedAt     time.Time `json:"created_at"`
	Id            string    `json:"id"`

	// Priority Backlog ordering for the pull; higher pulls first.
	Priority int `json:"priority"`

	// ReadyAt Set by mark_ready; the pull's tie-breaker (03 §5).
	ReadyAt *time.Time `json:"ready_at,omitempty"`

	// State One of the five board states (03 §2.1). Render mapping: shaping/ ready -> Backlog; working/blocked -> Developing (blocked stacked above working); done -> Done.
	State     TicketState `json:"state"`
	Title     string      `json:"title"`
	UpdatedAt time.Time   `json:"updated_at"`
}

// TicketState One of the five board states (03 §2.1). Render mapping: shaping/ ready -> Backlog; working/blocked -> Developing (blocked stacked above working); done -> Done.
type TicketState string

// GetMessagesParams defines parameters for GetMessages.
type GetMessagesParams struct {
	// Limit Maximum number of most-recent rows to return.
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// PostMessageJSONRequestBody defines body for PostMessage for application/json ContentType.
type PostMessageJSONRequestBody = MessageRequest
