// Package wire provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package wire

import (
	"time"
)

// Defines values for ActivityEventKind.
const (
	Thinking ActivityEventKind = "thinking"
	Toast    ActivityEventKind = "toast"
)

// Valid indicates whether the value is a known member of the ActivityEventKind enum.
func (e ActivityEventKind) Valid() bool {
	switch e {
	case Thinking:
		return true
	case Toast:
		return true
	default:
		return false
	}
}

// Defines values for ActivityEventVerb.
const (
	Finished ActivityEventVerb = "finished"
	Nudged   ActivityEventVerb = "nudged"
	Queued   ActivityEventVerb = "queued"
	Started  ActivityEventVerb = "started"
)

// Valid indicates whether the value is a known member of the ActivityEventVerb enum.
func (e ActivityEventVerb) Valid() bool {
	switch e {
	case Finished:
		return true
	case Nudged:
		return true
	case Queued:
		return true
	case Started:
		return true
	default:
		return false
	}
}

// Defines values for AgentStatusStatus.
const (
	Building AgentStatusStatus = "building"
	Errored  AgentStatusStatus = "errored"
	Idle     AgentStatusStatus = "idle"
	Starting AgentStatusStatus = "starting"
	Stopped  AgentStatusStatus = "stopped"
)

// Valid indicates whether the value is a known member of the AgentStatusStatus enum.
func (e AgentStatusStatus) Valid() bool {
	switch e {
	case Building:
		return true
	case Errored:
		return true
	case Idle:
		return true
	case Starting:
		return true
	case Stopped:
		return true
	default:
		return false
	}
}

// Defines values for FeedCardKind.
const (
	FeedCardKindBlocker  FeedCardKind = "blocker"
	FeedCardKindDone     FeedCardKind = "done"
	FeedCardKindPoke     FeedCardKind = "poke"
	FeedCardKindPreview  FeedCardKind = "preview"
	FeedCardKindProposal FeedCardKind = "proposal"
	FeedCardKindUpdate   FeedCardKind = "update"
)

// Valid indicates whether the value is a known member of the FeedCardKind enum.
func (e FeedCardKind) Valid() bool {
	switch e {
	case FeedCardKindBlocker:
		return true
	case FeedCardKindDone:
		return true
	case FeedCardKindPoke:
		return true
	case FeedCardKindPreview:
		return true
	case FeedCardKindProposal:
		return true
	case FeedCardKindUpdate:
		return true
	default:
		return false
	}
}

// Defines values for HealthStatus.
const (
	HealthStatusOk HealthStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case HealthStatusOk:
		return true
	default:
		return false
	}
}

// Defines values for MeProjectMergeGateMode.
const (
	MeProjectMergeGateModeMain MeProjectMergeGateMode = "main"
	MeProjectMergeGateModePr   MeProjectMergeGateMode = "pr"
)

// Valid indicates whether the value is a known member of the MeProjectMergeGateMode enum.
func (e MeProjectMergeGateMode) Valid() bool {
	switch e {
	case MeProjectMergeGateModeMain:
		return true
	case MeProjectMergeGateModePr:
		return true
	default:
		return false
	}
}

// Defines values for MessageRole.
const (
	Kiln MessageRole = "kiln"
	User MessageRole = "user"
)

// Valid indicates whether the value is a known member of the MessageRole enum.
func (e MessageRole) Valid() bool {
	switch e {
	case Kiln:
		return true
	case User:
		return true
	default:
		return false
	}
}

// Defines values for NotificationModeMode.
const (
	All     NotificationModeMode = "all"
	Blocked NotificationModeMode = "blocked"
	Default NotificationModeMode = "default"
)

// Valid indicates whether the value is a known member of the NotificationModeMode enum.
func (e NotificationModeMode) Valid() bool {
	switch e {
	case All:
		return true
	case Blocked:
		return true
	case Default:
		return true
	default:
		return false
	}
}

// Defines values for ProjectUpdateRequestMergeGateMode.
const (
	ProjectUpdateRequestMergeGateModeMain ProjectUpdateRequestMergeGateMode = "main"
	ProjectUpdateRequestMergeGateModePr   ProjectUpdateRequestMergeGateMode = "pr"
)

// Valid indicates whether the value is a known member of the ProjectUpdateRequestMergeGateMode enum.
func (e ProjectUpdateRequestMergeGateMode) Valid() bool {
	switch e {
	case ProjectUpdateRequestMergeGateModeMain:
		return true
	case ProjectUpdateRequestMergeGateModePr:
		return true
	default:
		return false
	}
}

// Defines values for TicketState.
const (
	TicketStateBlocked TicketState = "blocked"
	TicketStateDone    TicketState = "done"
	TicketStateReady   TicketState = "ready"
	TicketStateShaping TicketState = "shaping"
	TicketStateWorking TicketState = "working"
)

// Valid indicates whether the value is a known member of the TicketState enum.
func (e TicketState) Valid() bool {
	switch e {
	case TicketStateBlocked:
		return true
	case TicketStateDone:
		return true
	case TicketStateReady:
		return true
	case TicketStateShaping:
		return true
	case TicketStateWorking:
		return true
	default:
		return false
	}
}

// Defines values for VerifyCheckName.
const (
	Amika     VerifyCheckName = "amika"
	Anthropic VerifyCheckName = "anthropic"
	Devin     VerifyCheckName = "devin"
	Repo      VerifyCheckName = "repo"
)

// Valid indicates whether the value is a known member of the VerifyCheckName enum.
func (e VerifyCheckName) Valid() bool {
	switch e {
	case Amika:
		return true
	case Anthropic:
		return true
	case Devin:
		return true
	case Repo:
		return true
	default:
		return false
	}
}

// Defines values for VerifyCheckStatus.
const (
	VerifyCheckStatusFailed  VerifyCheckStatus = "failed"
	VerifyCheckStatusOk      VerifyCheckStatus = "ok"
	VerifyCheckStatusSkipped VerifyCheckStatus = "skipped"
)

// Valid indicates whether the value is a known member of the VerifyCheckStatus enum.
func (e VerifyCheckStatus) Valid() bool {
	switch e {
	case VerifyCheckStatusFailed:
		return true
	case VerifyCheckStatusOk:
		return true
	case VerifyCheckStatusSkipped:
		return true
	default:
		return false
	}
}

// ActivityEvent The `activity` SSE event payload (08 §4) — ephemeral, never stored. `thinking` brackets a brain pass (renders the spinner); `toast` confirms one side-effect board transition (renders the auto-dismissing pill). Fields are keyed by `kind`, mirroring Ticket.state's enum discriminator.
type ActivityEvent struct {
	Kind ActivityEventKind `json:"kind"`

	// On For kind=thinking — true when a pass starts, false when it ends.
	On *bool `json:"on,omitempty"`

	// TicketId For kind=toast — the affected ticket's id, so tapping the toast opens that ticket's detail view. Absent on a say pill, which names no ticket.
	TicketId *string `json:"ticket_id,omitempty"`

	// TicketTitle For kind=toast — the affected ticket's title.
	TicketTitle *string `json:"ticket_title,omitempty"`

	// Verb For kind=toast — the transition: started (dispatched), nudged (new turn sent), finished (accepted to done), queued (marked ready).
	Verb *ActivityEventVerb `json:"verb,omitempty"`
}

// ActivityEventKind defines model for ActivityEvent.Kind.
type ActivityEventKind string

// ActivityEventVerb For kind=toast — the transition: started (dispatched), nudged (new turn sent), finished (accepted to done), queued (marked ready).
type ActivityEventVerb string

// ActivityStatus GET /api/activity response (08 §4) — the current value of the `thinking` bracket, pulled by the client on foreground/resume and stream reconnect to resync the spinner. Server-authoritative: the client never writes it (it is derived from whether a brain pass is in flight), so this is a read-only snapshot, not a settable state.
type ActivityStatus struct {
	// Thinking True while a brain pass is in flight (the spinner is showing).
	Thinking bool `json:"thinking"`
}

// AgentStatus One live worker's real underlying session status, joined to its most-recent ticket binding (amended 2026-07-05). This is the actual agent/session running state — distinct from a ticket's board-column placement — so the Streams view can show a stopped or errored session instead of a hardcoded "building". worker_id is the board slot uuid; ticket_id is "" for an idle-pool worker that never ran a send.
type AgentStatus struct {
	// Status building = alive with a turn in flight; idle = alive, no turn; stopped = session auto-stopped/not running; errored = terminal session failure; starting = session provisioning, not reachable yet.
	Status   AgentStatusStatus `json:"status"`
	TicketId string            `json:"ticket_id"`
	WorkerId string            `json:"worker_id"`
}

// AgentStatusStatus building = alive with a turn in flight; idle = alive, no turn; stopped = session auto-stopped/not running; errored = terminal session failure; starting = session provisioning, not reachable yet.
type AgentStatusStatus string

// AmikaSecret One Amika secret injected into every sandbox this project starts (02 §8): `name` is the environment-variable name it lands under inside the sandbox (the user-facing label), and `value` is the presence+fingerprint of the secret value — never the value itself (11 §3 D7). The value is encrypted at rest and write-only, so reads only ever carry its status.
type AmikaSecret struct {
	Name  string       `json:"name"`
	Value SecretStatus `json:"value"`
}

// AmikaSecretInput One Amika secret on a project upsert (02 §8). `name` is the environment variable it is injected as; `value` is write-only — a non-empty value sets/replaces the stored (encrypted) secret, and an omitted or empty value keeps the value already stored for that name (the credential-merge convention, 11 §3 D7). A name dropped from the list clears that secret.
type AmikaSecretInput struct {
	Name  string  `json:"name"`
	Value *string `json:"value,omitempty"`
}

// BetaSignupRequest POST /api/beta-signup body — the visitor's email for the beta list.
type BetaSignupRequest struct {
	// Email The visitor's email. Kept a plain string on the wire (no format:email, which would pull an openapi_types dependency into the generated Go); the server validates it parses as a real address (net/mail).
	Email string `json:"email"`
}

// Board GetBoard's full snapshot (03 §4), grouped in render order — the `board` SSE event payload and GET /api/board's response body are the identical shape (04 D7): absolute, never a delta, so a reconnect's resync is just "render the next board event" (07 §7–§8). `ready` is in exact pull order, top-to-bottom, so the user sees what gets pulled next (03 §5, 07 §7).
type Board struct {
	// Agents Live workers with their real session status, joined server-side for the Streams view (amended 2026-07-05). Absolute like the rest of the snapshot; empty before the first worker is live. Keyed to tickets by ticket_id.
	Agents []AgentStatus `json:"agents"`

	// Alerts Persistent system-health problems to surface as a permanent error band above the dock. Absolute like the rest of the snapshot: an alert stays present across snapshots until its condition clears, then drops out. Empty in the healthy steady state.
	Alerts  []SystemAlert `json:"alerts"`
	Blocked []Ticket      `json:"blocked"`
	Done    []Ticket      `json:"done"`
	Ready   []Ticket      `json:"ready"`
	Shaping []Ticket      `json:"shaping"`

	// WorkerFree Free (non-busy) worker slots — the capacity chip (07 §7).
	WorkerFree int `json:"worker_free"`

	// WorkerTotal Total worker capacity slots (03 §2.3).
	WorkerTotal int      `json:"worker_total"`
	Working     []Ticket `json:"working"`
}

// FeedCard One backlog item on the primary screen (08 §3). Hybrid-sourced but the client renders one list and never knows the difference: `blocker` and `proposal` are derived from board state; `update` and `preview` are brain-authored notification rows. The visible tag (Blocker/Proposal/ Update/Preview) is derived from `kind` on the client.
type FeedCard struct {
	Body string `json:"body"`

	// CreatedAt When the card became current (blocked-at for blockers, request time for proposals, post time for notes); drives the relative age label.
	CreatedAt time.Time `json:"created_at"`

	// GithubLabel Set for done cards alongside github_url — the clickable link text: the abbreviated commit SHA, or "#<number>" for a pull request.
	GithubLabel *string `json:"github_label,omitempty"`

	// GithubUrl Set for done cards — the GitHub web page for the landed work (the commit on origin/main under merge-on-main, or the pull request under the PR gate). The card's second line links here (08 §7).
	GithubUrl *string `json:"github_url,omitempty"`

	// Id Stable render key. `blocker:<ticket_id>`, `proposal:<ticket_id>`, or `update:<notification_id>`.
	Id string `json:"id"`

	// ImageUrl Set for preview cards — the embedded render (08 §3, 4c).
	ImageUrl *string `json:"image_url,omitempty"`

	// Kind blocker -> ticket in the Blocked zone (body is blocked_reason); proposal -> Shaping ticket with approval_requested (body is the shaped summary, Accept affordance shown); update -> brain-authored note; preview -> brain-authored note with an image; poke -> mechanical stall nudge (body empty; the ticket title carries a 👉); done -> mechanical completion card (body empty; the ticket title carries a ✅).
	Kind FeedCardKind `json:"kind"`

	// Label The short stream/ticket label shown above the card body (e.g. the ticket title). May be empty for an authored note with no linked ticket.
	Label string `json:"label"`

	// NotificationId Set for update/preview cards; the id the client passes to /api/feed/seen as the high-water mark (08 §3).
	NotificationId *int64 `json:"notification_id,omitempty"`

	// TicketId Set for blocker/proposal (the derived ticket); optional for authored notes.
	TicketId *string `json:"ticket_id,omitempty"`

	// WorkSummary Set for done cards — the full description of the landed work: the entire commit message (subject + body) under the main merge gate, or the pull-request title + description under the PR gate. Rendered as the card's expandable body — the client previews the first lines and reveals the rest on tap (08 §7). Null when unavailable.
	WorkSummary *string `json:"work_summary,omitempty"`
}

// FeedCardKind blocker -> ticket in the Blocked zone (body is blocked_reason); proposal -> Shaping ticket with approval_requested (body is the shaped summary, Accept affordance shown); update -> brain-authored note; preview -> brain-authored note with an image; poke -> mechanical stall nudge (body empty; the ticket title carries a 👉); done -> mechanical completion card (body empty; the ticket title carries a ✅).
type FeedCardKind string

// FeedHistoryPage One older page of retained update/preview history (GET /api/feed/history — 08 §3, D2′): notification-backed cards only, newest-first, older than the request's `before` cursor. Board-derived blocker/proposal cards are never paged.
type FeedHistoryPage struct {
	Cards []FeedCard `json:"cards"`

	// HasMore True when another older page remains beyond this one.
	HasMore bool `json:"has_more"`
}

// FeedSeenRequest POST /api/feed/seen body (08 §3) — the seen high-water mark.
type FeedSeenRequest struct {
	LastNotificationId int64 `json:"last_notification_id"`
}

// FeedSnapshot GET /api/feed's body and the `feed` SSE event payload — the identical absolute shape (08 §3, D2′). `cards` is in strict order: unresolved blockers, then pending proposals, then updates newest-first (seen and unseen — retained history). `cards` carries only the NEWEST PAGE of updates; `has_more_history` signals older ones are pageable via /api/feed/history.
type FeedSnapshot struct {
	Cards []FeedCard `json:"cards"`

	// HasMoreHistory True when retained update/preview history exists older than the oldest update card in `cards` — page it in via GET /api/feed/history (08 D2′).
	HasMoreHistory bool `json:"has_more_history"`

	// Summary Server-derived header status counts (08 §2). The client renders the one-line summary from these: "N blocker(s) · M updates" when blockers exist, the active-stream count ("K streams") when not, "Nothing active" when the feed is empty; plus the all-clear detail line (building/idle/last word).
	Summary FeedSummary `json:"summary"`
}

// FeedSummary Server-derived header status counts (08 §2). The client renders the one-line summary from these: "N blocker(s) · M updates" when blockers exist, the active-stream count ("K streams") when not, "Nothing active" when the feed is empty; plus the all-clear detail line (building/idle/last word).
type FeedSummary struct {
	BlockerCount int `json:"blocker_count"`

	// Building Streams with a worker actively building (working).
	Building int `json:"building"`

	// Idle Active streams not currently building.
	Idle int `json:"idle"`

	// LastSeenNotificationId The persistent seen high-water mark (08 D2′): the greatest notification id the user has acked. Update/preview cards with a greater notification_id are "new since last visit" (above the last-seen divider); those at or below it are retained history (below it). Null when nothing has ever been seen. The client freezes this at the first snapshot of a session so marking-seen-on-view doesn't move the divider mid-session.
	LastSeenNotificationId *int64 `json:"last_seen_notification_id,omitempty"`

	// LastWordAt Timestamp of the most recent brain say/update, for "last word 6m ago".
	LastWordAt *time.Time `json:"last_word_at,omitempty"`

	// StreamCount Number of active ticket streams (working + blocked).
	StreamCount int `json:"stream_count"`

	// UpdateCount Count of unseen update/preview cards.
	UpdateCount int `json:"update_count"`
}

// Health defines model for Health.
type Health struct {
	Status  HealthStatus `json:"status"`
	Version string       `json:"version"`
}

// HealthStatus defines model for Health.Status.
type HealthStatus string

// Me The signed-in user's account view (11 §4). Secret values never appear.
type Me struct {
	// Project Absent until the user creates their project.
	Project *MeProject `json:"project,omitempty"`

	// Providers The coding-agent providers this deployment offers (multi-provider design §8, §9), one descriptor per registered provider. The project form renders its provider select from this — a deployment that offers only one provider shows a single option (or hides the select). Omitted when the deployment has not enabled the descriptor surface.
	Providers *[]ProviderDescriptor `json:"providers,omitempty"`

	// Settings Config status — secrets as presence+fingerprint only (11 §3 D7).
	Settings MeSettings `json:"settings"`
	User     MeUser     `json:"user"`
}

// MeProject defines model for MeProject.
type MeProject struct {
	// AgentProvider The registry key selecting which coding-agent provider this project's turns run on (multi-provider design §9): `amika`, `devin`, `mock`, … Empty means "use the deployment default" (AGENT_MODE) — the back-compat behavior every existing project keeps.
	AgentProvider string `json:"agent_provider"`

	// AmikaSecrets Amika secrets injected into every sandbox this project starts (02 §8).
	AmikaSecrets  []AmikaSecret `json:"amika_secrets"`
	AmikaSnapshot string        `json:"amika_snapshot"`

	// MergeGateMode Which condition satisfies a ticket's merge gate (06 §7): `main` accepts a done only once its commit is on origin/main; `pr` accepts it once the work exists in a pull request, merged or not. Defaults to `main`.
	MergeGateMode MeProjectMergeGateMode `json:"merge_gate_mode"`
	Name          string                 `json:"name"`
	RepoUrl       string                 `json:"repo_url"`
	WorkerCount   int                    `json:"worker_count"`
}

// MeProjectMergeGateMode Which condition satisfies a ticket's merge gate (06 §7): `main` accepts a done only once its commit is on origin/main; `pr` accepts it once the work exists in a pull request, merged or not. Defaults to `main`.
type MeProjectMergeGateMode string

// MeSettings Config status — secrets as presence+fingerprint only (11 §3 D7).
type MeSettings struct {
	AmikaApiKey       SecretStatus `json:"amika_api_key"`
	AmikaClaudeCredId string       `json:"amika_claude_cred_id"`
	AnthropicApiKey   SecretStatus `json:"anthropic_api_key"`
	DevinApiKey       SecretStatus `json:"devin_api_key"`
	GithubAuthToken   SecretStatus `json:"github_auth_token"`
}

// MeUser defines model for MeUser.
type MeUser struct {
	AvatarUrl   string `json:"avatar_url"`
	DisplayName string `json:"display_name"`
	GithubLogin string `json:"github_login"`
}

// Message One persisted transcript row (07 §3), as returned oldest-first by GET /api/messages.
type Message struct {
	MessageId int64       `json:"message_id"`
	Role      MessageRole `json:"role"`
	Text      string      `json:"text"`
	Timestamp time.Time   `json:"timestamp"`
}

// MessageRole defines model for Message.Role.
type MessageRole string

// MessagePostResponse POST /api/message's 202 body (07 §4) — both ids the client needs to reconcile its optimistic send.
type MessagePostResponse struct {
	EventId   int64 `json:"event_id"`
	MessageId int64 `json:"message_id"`
}

// MessageRequest POST /api/message body (07 §4). Text only in v1; 09 adds STT in front of this seam.
type MessageRequest struct {
	Text string `json:"text"`
}

// NotificationMode The global push-notification frequency (02 §10). `default` — the recommended setting — sends a push on the genuine ticket milestones (blocked, completed, started); `blocked` narrows that to only the blocked transition (a push only when a ticket needs a human decision); `all` sends a push on every feed update, a testing aid for confirming push delivery. Extensible: more modes may be added later.
type NotificationMode struct {
	// Mode Which ticket events fire a push notification.
	Mode NotificationModeMode `json:"mode"`
}

// NotificationModeMode Which ticket events fire a push notification.
type NotificationModeMode string

// PresenceUpdate One device's foreground-presence report (02 §10 push dedup): whether the app is currently visible, plus the device's own push-subscription endpoint so the server stamps the right row. The server uses its own clock, so no timestamp is carried.
type PresenceUpdate struct {
	// Endpoint The push service URL identifying this device's subscription row (the same endpoint carried in PushSubscription).
	Endpoint string `json:"endpoint"`

	// Visible true while the tab is foregrounded (heartbeat); false on the best-effort leave beacon when it backgrounds.
	Visible bool `json:"visible"`
}

// ProjectUpdateRequest defines model for ProjectUpdateRequest.
type ProjectUpdateRequest struct {
	// AgentProvider The registry key selecting this project's coding-agent provider (multi-provider design §9). Omitted or empty selects the deployment default (AGENT_MODE). The composition root validates the key against the registered provider set; an unregistered key pauses the project's board loud rather than silently falling back (D7).
	AgentProvider *string `json:"agent_provider,omitempty"`

	// AmikaSecrets The project's full Amika secret list. Like the other optional project fields on this wholesale upsert, omitted or [] clears it; a name kept with an empty value keeps its stored (encrypted) value (02 §8).
	AmikaSecrets  *[]AmikaSecretInput `json:"amika_secrets,omitempty"`
	AmikaSnapshot *string             `json:"amika_snapshot,omitempty"`

	// MergeGateMode Which condition satisfies a ticket's merge gate (06 §7): `main` (done when the commit is on origin/main) or `pr` (done when the work is in a pull request). Omitted or empty keeps/defaults to `main`.
	MergeGateMode *ProjectUpdateRequestMergeGateMode `json:"merge_gate_mode,omitempty"`
	Name          string                             `json:"name"`
	RepoUrl       string                             `json:"repo_url"`
	WorkerCount   *int                               `json:"worker_count,omitempty"`
}

// ProjectUpdateRequestMergeGateMode Which condition satisfies a ticket's merge gate (06 §7): `main` (done when the commit is on origin/main) or `pr` (done when the work is in a pull request). Omitted or empty keeps/defaults to `main`.
type ProjectUpdateRequestMergeGateMode string

// ProviderCapabilities A provider's declared shape (multi-provider design §5), read by the dashboard to light up or hide capability-gated affordances (e.g. a workspace-reset button only for a managed-sandbox provider) without naming the provider.
type ProviderCapabilities struct {
	ManagedSandbox bool `json:"managed_sandbox"`
	ReportsCost    bool `json:"reports_cost"`
	SecretsInject  bool `json:"secrets_inject"`
	Snapshots      bool `json:"snapshots"`
}

// ProviderDescriptor A registered coding-agent provider the dashboard can offer (multi-provider design §8, D6). Data-driven so the generic dashboard names no provider: the select is rendered from these, not from hard-coded Amika/Devin inputs.
type ProviderDescriptor struct {
	// Capabilities A provider's declared shape (multi-provider design §5), read by the dashboard to light up or hide capability-gated affordances (e.g. a workspace-reset button only for a managed-sandbox provider) without naming the provider.
	Capabilities ProviderCapabilities `json:"capabilities"`

	// Key The registry key stored as a project's agent_provider (amika, devin, mock, …).
	Key string `json:"key"`

	// Label Human-facing name shown in the provider select (e.g. "Amika", "Devin").
	Label string `json:"label"`
}

// PushKey The VAPID public key for pushManager.subscribe (02 §10).
type PushKey struct {
	// Key Base64url-encoded VAPID application server key.
	Key string `json:"key"`
}

// PushSubscription A browser PushSubscription as produced by `PushSubscription.toJSON()` — the endpoint URL plus the p256dh and auth keys used to encrypt Web Push payloads (RFC 8291).
type PushSubscription struct {
	// Endpoint The push service URL messages are POSTed to.
	Endpoint string `json:"endpoint"`
	Keys     struct {
		// Auth Base64url client auth secret.
		Auth string `json:"auth"`

		// P256dh Base64url client public key (ECDH P-256).
		P256dh string `json:"p256dh"`
	} `json:"keys"`
}

// PushUnsubscribe Identifies a browser push subscription to remove by its endpoint URL — the same endpoint carried in PushSubscription. No keys are needed to delete.
type PushUnsubscribe struct {
	// Endpoint The push service URL of the subscription to remove.
	Endpoint string `json:"endpoint"`
}

// SayEvent The `say` SSE event payload (07 §4) — one event per brain say (renamed from `speak`, 07 A1). message_id matches the corresponding Message row from GET /api/messages/the transcript.
type SayEvent struct {
	At        time.Time `json:"at"`
	MessageId int64     `json:"message_id"`
	Text      string    `json:"text"`
}

// SecretStatus defines model for SecretStatus.
type SecretStatus struct {
	Set bool `json:"set"`

	// Tail Last 4 characters of the stored secret; empty when unset.
	Tail string `json:"tail"`
}

// SettingsUpdateRequest All fields optional; empty or omitted means unchanged (write-only secrets).
type SettingsUpdateRequest struct {
	AmikaApiKey       *string `json:"amika_api_key,omitempty"`
	AmikaClaudeCredId *string `json:"amika_claude_cred_id,omitempty"`
	AnthropicApiKey   *string `json:"anthropic_api_key,omitempty"`
	DevinApiKey       *string `json:"devin_api_key,omitempty"`
	GithubAuthToken   *string `json:"github_auth_token,omitempty"`
}

// SystemAlert A persistent system-health problem surfaced to the user as a permanent error band above the dock — distinct from an auto-dismissing activity toast (08 §4): it stays until the condition clears. Deliberately generic: the client renders any alert without knowing its cause, so the section works for any persistent failure, not just sandboxes. `kind` is an opaque machine category the client may theme off but must not depend on; `detail` is the human-readable sentence shown verbatim. Rides the board snapshot's `alerts` array, which is absolute like the rest of the snapshot — an alert simply drops out of the next snapshot once its underlying condition recovers.
type SystemAlert struct {
	// Detail Human-readable description shown verbatim (e.g. "2 of 5 sandboxes failing").
	Detail string `json:"detail"`

	// Kind Opaque machine category of the failure (e.g. `sandbox_health`). For theming/analytics only — the UI must render any kind.
	Kind string `json:"kind"`
}

// Ticket One ticket as rendered on the board (03 §2.2). Column/zone placement is derived from `state`, never carried as a separate field (03 D1).
type Ticket struct {
	// ApprovalRequested Set by the brain's request_approval tool on a Shaping ticket (08 §5); a narrower secondary "explicitly nudged for attention" signal. It no longer gates proposal-card visibility: every Shaping ticket surfaces as a `proposal` feed card regardless (08 §5, superseding D5). Cleared by mark_ready.
	ApprovalRequested bool `json:"approval_requested"`

	// BlockedReason Set iff state is blocked (03 I4); full text, shown on the card (07 §7).
	BlockedReason *string   `json:"blocked_reason,omitempty"`
	Body          string    `json:"body"`
	CreatedAt     time.Time `json:"created_at"`
	Id            string    `json:"id"`

	// Priority Backlog ordering for the pull; higher pulls first.
	Priority int `json:"priority"`

	// ReadyAt Set by mark_ready; the pull's tie-breaker (03 §5).
	ReadyAt *time.Time `json:"ready_at,omitempty"`

	// State One of the five board states (03 §2.1). Render mapping: shaping/ ready -> Backlog; working/blocked -> Developing (blocked stacked above working); done -> Done.
	State TicketState `json:"state"`

	// StateChangedAt When the ticket last entered its current `state` (03 §2.2). Advances only on a real state transition, never on a same-state mutation such as a Working->Working nudge — the true "time in status" clock the client renders as the ticket-row subtext.
	StateChangedAt time.Time `json:"state_changed_at"`
	Title          string    `json:"title"`

	// UpdatedAt Time of the ticket's last mutation of any kind (bumped by nudges too).
	UpdatedAt time.Time `json:"updated_at"`
}

// TicketState One of the five board states (03 §2.1). Render mapping: shaping/ ready -> Backlog; working/blocked -> Developing (blocked stacked above working); done -> Done.
type TicketState string

// VerifyCheck defines model for VerifyCheck.
type VerifyCheck struct {
	Message string            `json:"message"`
	Name    VerifyCheckName   `json:"name"`
	Status  VerifyCheckStatus `json:"status"`
}

// VerifyCheckName defines model for VerifyCheck.Name.
type VerifyCheckName string

// VerifyCheckStatus defines model for VerifyCheck.Status.
type VerifyCheckStatus string

// VerifyResponse defines model for VerifyResponse.
type VerifyResponse struct {
	Checks []VerifyCheck `json:"checks"`
}

// VoiceToken POST /api/voice/token's 200 body (09 §2, §6): a short-lived AssemblyAI Universal-Streaming token and its absolute expiry. The client opens the STT WebSocket with `token` and refreshes proactively before `expires_at`.
type VoiceToken struct {
	// ExpiresAt Absolute expiry (backend-computed from the provider's redemption window).
	ExpiresAt time.Time `json:"expires_at"`

	// Token The temporary AssemblyAI streaming token (bearer for the wss connection).
	Token string `json:"token"`
}

// GetFeedHistoryParams defines parameters for GetFeedHistory.
type GetFeedHistoryParams struct {
	// Before Exclusive upper-bound notification id; returns cards with id < before. Omit for the newest page.
	Before *int64 `form:"before,omitempty" json:"before,omitempty"`

	// Limit Page size (default 30, bounds 1–100).
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetMessagesParams defines parameters for GetMessages.
type GetMessagesParams struct {
	// Limit Maximum number of most-recent rows to return.
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// PostBetaSignupJSONRequestBody defines body for PostBetaSignup for application/json ContentType.
type PostBetaSignupJSONRequestBody = BetaSignupRequest

// PostFeedSeenJSONRequestBody defines body for PostFeedSeen for application/json ContentType.
type PostFeedSeenJSONRequestBody = FeedSeenRequest

// PostMessageJSONRequestBody defines body for PostMessage for application/json ContentType.
type PostMessageJSONRequestBody = MessageRequest

// PostPresenceJSONRequestBody defines body for PostPresence for application/json ContentType.
type PostPresenceJSONRequestBody = PresenceUpdate

// PutProjectJSONRequestBody defines body for PutProject for application/json ContentType.
type PutProjectJSONRequestBody = ProjectUpdateRequest

// PutPushModeJSONRequestBody defines body for PutPushMode for application/json ContentType.
type PutPushModeJSONRequestBody = NotificationMode

// DeletePushSubscribeJSONRequestBody defines body for DeletePushSubscribe for application/json ContentType.
type DeletePushSubscribeJSONRequestBody = PushUnsubscribe

// PostPushSubscribeJSONRequestBody defines body for PostPushSubscribe for application/json ContentType.
type PostPushSubscribeJSONRequestBody = PushSubscription

// PutSettingsJSONRequestBody defines body for PutSettings for application/json ContentType.
type PutSettingsJSONRequestBody = SettingsUpdateRequest
