/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe. */
        get: operations["getHealthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/board": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Full board snapshot (03 §4 GetBoard; 04 §7).
         * @description The same absolute snapshot the `board` SSE event carries — for initial render before /api/stream attaches, or a manual resync (04 §7). Never a delta (03 D7).
         */
        get: operations["getBoard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/message": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send a user chat message (07 §3–§4, amending 04 §7).
         * @description Transactional transcript append (role=user) + EnqueueEvent (human.message, payload {text}) in one transaction — the transcript and the event queue cannot disagree (07 §3). `09` puts STT in front of this same seam without changing it.
         */
        post: operations["postMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Recent transcript rows, oldest-first (07 §4).
         * @description New in 07: initial chat-panel render and the post-reconnect reconciliation fetch (07 §5, §8).
         */
        get: operations["getMessages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/feed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Full feed snapshot for the primary screen (08 §3).
         * @description The same absolute snapshot the `feed` SSE event carries — for initial render before /api/stream attaches, or a manual resync (08 §3, mirroring 04 D7). Assembled server-side (08 §7): derived blocker/proposal cards from board state joined with unseen, unretracted brain-authored update/ preview notifications, in strict order (blockers -> proposals -> updates newest-first). Never a delta.
         */
        get: operations["getFeed"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/feed/seen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ack that update cards up to a high-water mark were seen (08 §3).
         * @description Inbox-drains semantics (08 D2): stamps seen_at on every unseen notification with id <= last_notification_id; seen updates drop out of subsequent feed snapshots. Blockers and proposals ignore seen entirely. Fired by the client when update cards render on a foregrounded, visible screen (08 §3).
         */
        post: operations["postFeedSeen"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tickets/{id}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Accept a proposal (08 §5).
         * @description Tap-accept on a proposal card. Per this project's decision (overriding 08 D6), acceptance routes through the brain: this appends a user transcript row and enqueues a human.message event expressing the acceptance, exactly like POST /api/message. The brain then marks the ticket Ready via mark_ready. Voice accept flows through the same brain path (08 §5).
         */
        post: operations["acceptTicket"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/voice/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mint a short-lived AssemblyAI streaming token (09 §6).
         * @description The client calls this, then opens AssemblyAI's Universal-Streaming WebSocket directly with the returned token — audio never transits the Kiln backend, and the real API key never leaves /backend (09 §2, 02 §2). Thin handler over the STT-provider port; the concrete AssemblyAI client lives in infra and is wired at the composition root. Token expiry is <= 10 min (09 §6).
         */
        post: operations["postVoiceToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * SSE stream of `board`, `say`, `feed`, and `activity` events (04 §7, 07 §4, 08 §3–§4).
         * @description Server-sent events; not a JSON response. Four named SSE event types ride this one connection: `board` (payload: Board — the full snapshot, sent immediately on connect and again per board.updated outbox entry, absolute and never a delta — 03 D7/04 D7); `say` (payload: SayEvent — one per brain say, renamed from `speak`, 07 A1); `feed` (payload: FeedSnapshot — the full visible feed, sent per feed.updated outbox entry, absolute; reconnect's resync is the next `feed` event — 08 §3); and `activity` (payload: ActivityEvent — ephemeral, SSE-only, never stored: thinking on/off and per-transition action toasts — 08 §4). Comment-line keepalive every 25s. `Last-Event-ID` is unused. This operation is declared for documentation and so the payload schemas below generate into both sides' types; the actual response content type is `text/event-stream`.
         */
        get: operations["getStream"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Health: {
            /** @enum {string} */
            status: "ok";
            version: string;
        };
        /** @description One ticket as rendered on the board (03 §2.2). Column/zone placement is derived from `state`, never carried as a separate field (03 D1). */
        Ticket: {
            id: string;
            title: string;
            body: string;
            /**
             * @description One of the five board states (03 §2.1). Render mapping: shaping/ ready -> Backlog; working/blocked -> Developing (blocked stacked above working); done -> Done.
             * @enum {string}
             */
            state: "shaping" | "ready" | "working" | "blocked" | "done";
            /** @description Backlog ordering for the pull; higher pulls first. */
            priority: number;
            /** @description Set by the brain's request_approval tool on a Shaping ticket (08 §5); a narrower secondary "explicitly nudged for attention" signal. It no longer gates proposal-card visibility: every Shaping ticket surfaces as a `proposal` feed card regardless (08 §5, superseding D5). Cleared by mark_ready. */
            approval_requested: boolean;
            /** @description Set iff state is blocked (03 I4); full text, shown on the card (07 §7). */
            blocked_reason?: string | null;
            /**
             * Format: date-time
             * @description Set by mark_ready; the pull's tie-breaker (03 §5).
             */
            ready_at?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        /** @description GetBoard's full snapshot (03 §4), grouped in render order — the `board` SSE event payload and GET /api/board's response body are the identical shape (04 D7): absolute, never a delta, so a reconnect's resync is just "render the next board event" (07 §7–§8). `ready` is in exact pull order, top-to-bottom, so the user sees what gets pulled next (03 §5, 07 §7). */
        Board: {
            shaping: components["schemas"]["Ticket"][];
            ready: components["schemas"]["Ticket"][];
            blocked: components["schemas"]["Ticket"][];
            working: components["schemas"]["Ticket"][];
            done: components["schemas"]["Ticket"][];
            /** @description Total worker capacity slots (03 §2.3). */
            worker_total: number;
            /** @description Free (non-busy) worker slots — the capacity chip (07 §7). */
            worker_free: number;
        };
        /** @description One persisted transcript row (07 §3), as returned oldest-first by GET /api/messages. */
        Message: {
            /** Format: int64 */
            message_id: number;
            /** @enum {string} */
            role: "user" | "kiln";
            text: string;
            /** Format: date-time */
            timestamp: string;
        };
        /** @description POST /api/message body (07 §4). Text only in v1; 09 adds STT in front of this seam. */
        MessageRequest: {
            text: string;
        };
        /** @description POST /api/message's 202 body (07 §4) — both ids the client needs to reconcile its optimistic send. */
        MessagePostResponse: {
            /** Format: int64 */
            event_id: number;
            /** Format: int64 */
            message_id: number;
        };
        /** @description The `say` SSE event payload (07 §4) — one event per brain say (renamed from `speak`, 07 A1). message_id matches the corresponding Message row from GET /api/messages/the transcript. */
        SayEvent: {
            /** Format: int64 */
            message_id: number;
            text: string;
            /** Format: date-time */
            at: string;
        };
        /** @description POST /api/voice/token's 200 body (09 §2, §6): a short-lived AssemblyAI Universal-Streaming token and its absolute expiry. The client opens the STT WebSocket with `token` and refreshes proactively before `expires_at`. */
        VoiceToken: {
            /** @description The temporary AssemblyAI streaming token (bearer for the wss connection). */
            token: string;
            /**
             * Format: date-time
             * @description Absolute expiry (backend-computed from the provider's redemption window).
             */
            expires_at: string;
        };
        /** @description One backlog item on the primary screen (08 §3). Hybrid-sourced but the client renders one list and never knows the difference: `blocker` and `proposal` are derived from board state; `update` and `preview` are brain-authored notification rows. The visible tag (Blocker/Proposal/ Update/Preview) is derived from `kind` on the client. */
        FeedCard: {
            /**
             * @description blocker -> ticket in the Blocked zone (body is blocked_reason); proposal -> Shaping ticket with approval_requested (body is the shaped summary, Accept affordance shown); update -> brain-authored note; preview -> brain-authored note with an image.
             * @enum {string}
             */
            kind: "blocker" | "proposal" | "update" | "preview";
            /** @description Stable render key. `blocker:<ticket_id>`, `proposal:<ticket_id>`, or `update:<notification_id>`. */
            id: string;
            /** @description The short stream/ticket label shown above the card body (e.g. the ticket title). May be empty for an authored note with no linked ticket. */
            label: string;
            body: string;
            /** @description Set for blocker/proposal (the derived ticket); optional for authored notes. */
            ticket_id?: string | null;
            /**
             * Format: int64
             * @description Set for update/preview cards; the id the client passes to /api/feed/seen as the high-water mark (08 §3).
             */
            notification_id?: number | null;
            /** @description Set for preview cards — the embedded render (08 §3, 4c). */
            image_url?: string | null;
            /**
             * Format: date-time
             * @description When the card became current (blocked-at for blockers, request time for proposals, post time for notes); drives the relative age label.
             */
            created_at: string;
        };
        /** @description Server-derived header status counts (08 §2). The client renders the one-line summary from these: "N blocker(s) · M updates" when blockers exist, "K streams · nothing needs you" when not, "all clear" when the feed is empty; plus the all-clear detail line (building/idle/last word). */
        FeedSummary: {
            blocker_count: number;
            /** @description Count of unseen update/preview cards. */
            update_count: number;
            /** @description Number of active ticket streams (working + blocked). */
            stream_count: number;
            /** @description Streams with a worker actively building (working). */
            building: number;
            /** @description Active streams not currently building. */
            idle: number;
            /**
             * Format: date-time
             * @description Timestamp of the most recent brain say/update, for "last word 6m ago".
             */
            last_word_at?: string | null;
        };
        /** @description GET /api/feed's body and the `feed` SSE event payload — the identical absolute shape (08 §3). `cards` is in strict order: unresolved blockers, then pending proposals, then unseen updates newest-first. */
        FeedSnapshot: {
            summary: components["schemas"]["FeedSummary"];
            cards: components["schemas"]["FeedCard"][];
        };
        /** @description POST /api/feed/seen body (08 §3) — the seen high-water mark. */
        FeedSeenRequest: {
            /** Format: int64 */
            last_notification_id: number;
        };
        /** @description The `activity` SSE event payload (08 §4) — ephemeral, never stored. `thinking` brackets a brain pass (renders the spinner); `toast` confirms one side-effect board transition (renders the auto-dismissing pill). Fields are keyed by `kind`, mirroring Ticket.state's enum discriminator. */
        ActivityEvent: {
            /** @enum {string} */
            kind: "thinking" | "toast";
            /** @description For kind=thinking — true when a pass starts, false when it ends. */
            on?: boolean | null;
            /**
             * @description For kind=toast — the transition: started (dispatched), nudged (new turn sent), finished (accepted to done), queued (marked ready).
             * @enum {string|null}
             */
            verb?: "started" | "nudged" | "finished" | "queued" | null;
            /** @description For kind=toast — the affected ticket's title. */
            ticket_title?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is up. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    getBoard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current board snapshot. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Board"];
                };
            };
        };
    };
    postMessage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MessageRequest"];
            };
        };
        responses: {
            /** @description Accepted — the user row is durably appended and the human.message event is enqueued. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessagePostResponse"];
                };
            };
        };
    };
    getMessages: {
        parameters: {
            query?: {
                /** @description Maximum number of most-recent rows to return. */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The most-recent `limit` transcript rows, oldest-first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"][];
                };
            };
        };
    };
    getFeed: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current feed snapshot. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedSnapshot"];
                };
            };
        };
    };
    postFeedSeen: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedSeenRequest"];
            };
        };
        responses: {
            /** @description Accepted — the seen high-water mark was stamped. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    acceptTicket: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The Shaping ticket's id (must have approval_requested set). */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accepted — the acceptance user row is appended and the human.message event is enqueued for the brain. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessagePostResponse"];
                };
            };
        };
    };
    postVoiceToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A temporary streaming token and its absolute expiry. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VoiceToken"];
                };
            };
            /** @description The STT provider failed to mint a token. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getStream: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description text/event-stream carrying `board` (Board), `say` (SayEvent), `feed` (FeedSnapshot), and `activity` (ActivityEvent) named SSE events. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
        };
    };
}
