/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe. */
        get: operations["getHealthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/board": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Full board snapshot (03 §4 GetBoard; 04 §7).
         * @description The same absolute snapshot the `board` SSE event carries — for initial render before /api/stream attaches, or a manual resync (04 §7). Never a delta (03 D7).
         */
        get: operations["getBoard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/message": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send a user chat message (07 §3–§4, amending 04 §7).
         * @description Transactional transcript append (role=user) + EnqueueEvent (human.message, payload {text}) in one transaction — the transcript and the event queue cannot disagree (07 §3). `09` puts STT in front of this same seam without changing it.
         */
        post: operations["postMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Recent transcript rows, oldest-first (07 §4).
         * @description New in 07: initial chat-panel render and the post-reconnect reconciliation fetch (07 §5, §8).
         */
        get: operations["getMessages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/feed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Full feed snapshot for the primary screen (08 §3, D2′).
         * @description The same absolute snapshot the `feed` SSE event carries — for initial render before /api/stream attaches, or a manual resync (08 §3, mirroring 04 D7). Assembled server-side (08 §7): derived blocker/proposal cards from board state joined with the NEWEST PAGE of unretracted brain-authored update/preview notifications — seen AND unseen (08 D2′, retained history), in strict order (blockers -> proposals -> updates newest-first). `summary.last_seen_notification_id` marks the last-seen divider boundary and `has_more_history` signals older updates are pageable via /api/feed/history. Never a delta.
         */
        get: operations["getFeed"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/feed/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * One older page of retained update/preview history (08 §3, D2′).
         * @description Keyset pagination over retained (unretracted) update/preview notifications, newest-first, older than the `before` cursor — the "Show earlier updates" affordance (08 §3, D2′). Blockers and proposals are board-derived and never paged; this returns only notification-backed cards. Mirrors the /api/messages `limit` convention. `before` omitted means start from the newest (rarely needed — GET /api/feed already carries the first page). `has_more` signals another page remains.
         */
        get: operations["getFeedHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/feed/seen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ack that update cards up to a high-water mark were seen (08 §3).
         * @description Retained-history semantics (08 D2′): stamps seen_at on every unseen notification with id <= last_notification_id, advancing the persistent last-seen high-water mark. Seen updates STAY in the feed as history below the last-seen divider (they no longer drop out); the mark only moves the divider on the next visit. Blockers and proposals ignore seen entirely. Fired by the client when update cards render on a foregrounded, visible screen (08 §3).
         */
        post: operations["postFeedSeen"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/feed/{id}/dismiss": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Clear (dismiss) a single update/preview card — swipe-to-dismiss (08 §3).
         * @description Clears one notification-backed feed card for good: retracts the notification behind it (the same stamp the brain's retract makes, but user-initiated by swiping the row left) so it drops from the feed and does not return on the next snapshot or reload. Only update/preview cards are dismissible — blockers and proposals are board-derived state the brain owns, not notifications, and have no id to dismiss. Emits feed.updated so the card leaves every open client. Idempotent: dismissing an already-gone or unknown id is a no-op and still returns 202.
         */
        post: operations["dismissFeedCard"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/feed/dismiss-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Clear (dismiss) every feed notification at once — the header trash affordance (08 §3).
         * @description Clears all notification-backed feed cards for good in one shot: retracts every still-active notification (the bulk sibling of the single-card dismiss), so they drop from the feed and none return on the next snapshot or reload. Board-derived cards (blockers and proposals) are untouched — they are board state the brain owns, not notifications. Emits one feed.updated so the cards leave every open client. Idempotent: clearing an already-empty feed is a no-op and still returns 202.
         */
        post: operations["dismissAllFeedCards"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tickets/{id}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Accept a proposal (08 §5).
         * @description Tap-accept on a proposal card. Per this project's decision (overriding 08 D6), acceptance routes through the brain: this appends a user transcript row and enqueues a human.message event expressing the acceptance, exactly like POST /api/message. The brain then marks the ticket Ready via mark_ready. Voice accept flows through the same brain path (08 §5).
         */
        post: operations["acceptTicket"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/voice/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mint a short-lived AssemblyAI streaming token (09 §6).
         * @description The client calls this, then opens AssemblyAI's Universal-Streaming WebSocket directly with the returned token — audio never transits the Kiln backend, and the real API key never leaves /backend (09 §2, 02 §2). Thin handler over the STT-provider port; the concrete AssemblyAI client lives in infra and is wired at the composition root. Token expiry is <= 10 min (09 §6).
         */
        post: operations["postVoiceToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/push/key": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The VAPID public key the client subscribes with (02 §10).
         * @description Returns the server's VAPID application server key, base64url-encoded, for the client's `pushManager.subscribe({ applicationServerKey })` call. The matching private key never leaves /backend. 404 when push is not configured (the VAPID env vars are unset) — the client treats that as "notifications unavailable" and hides the toggle.
         */
        get: operations["getPushKey"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/push/subscribe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register a browser push subscription (02 §10).
         * @description Stores the browser `PushSubscription` (endpoint + p256dh/auth keys) so the runtime's notify.send executor can deliver Web Push messages to it. Upsert on endpoint — a re-subscribe from the same browser is idempotent. Single user in v1: subscriptions are stored globally and every notification fans out to all of them.
         */
        post: operations["postPushSubscribe"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/push/mode": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The current push-notification frequency mode (02 §10).
         * @description Returns the global notification mode that gates when the runtime emits a Web Push message. `blocked` (the default) notifies only when a ticket needs a human decision; `all` notifies on every feed update (a testing aid). Single user in v1, so the mode is a single global value.
         */
        get: operations["getPushMode"];
        /**
         * Set the push-notification frequency mode (02 §10).
         * @description Persists the global notification mode. Takes effect on the next feed update; single user in v1, so it applies to every stored subscription.
         */
        put: operations["putPushMode"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * SSE stream of `board`, `say`, `feed`, and `activity` events (04 §7, 07 §4, 08 §3–§4).
         * @description Server-sent events; not a JSON response. Four named SSE event types ride this one connection: `board` (payload: Board — the full snapshot, sent immediately on connect and again per board.updated outbox entry, absolute and never a delta — 03 D7/04 D7); `say` (payload: SayEvent — one per brain say, renamed from `speak`, 07 A1); `feed` (payload: FeedSnapshot — the full visible feed, sent per feed.updated outbox entry, absolute; reconnect's resync is the next `feed` event — 08 §3); and `activity` (payload: ActivityEvent — ephemeral, SSE-only, never stored: thinking on/off and per-transition action toasts — 08 §4). Comment-line keepalive every 25s. `Last-Event-ID` is unused. This operation is declared for documentation and so the payload schemas below generate into both sides' types; the actual response content type is `text/event-stream`.
         */
        get: operations["getStream"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current user, project, and config status (11 §4). Session-protected. */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Partial credential update (11 §4). Secrets are write-only; empty/omitted fields are unchanged. */
        put: operations["putSettings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/project": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Create-or-update the caller's single project (11 §3–§4). */
        put: operations["putProject"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Live connection checks for stored credentials (11 §4). */
        post: operations["postSettingsVerify"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Health: {
            /** @enum {string} */
            status: "ok";
            version: string;
        };
        /** @description One ticket as rendered on the board (03 §2.2). Column/zone placement is derived from `state`, never carried as a separate field (03 D1). */
        Ticket: {
            id: string;
            title: string;
            body: string;
            /**
             * @description One of the five board states (03 §2.1). Render mapping: shaping/ ready -> Backlog; working/blocked -> Developing (blocked stacked above working); done -> Done.
             * @enum {string}
             */
            state: "shaping" | "ready" | "working" | "blocked" | "done";
            /** @description Backlog ordering for the pull; higher pulls first. */
            priority: number;
            /** @description Set by the brain's request_approval tool on a Shaping ticket (08 §5); a narrower secondary "explicitly nudged for attention" signal. It no longer gates proposal-card visibility: every Shaping ticket surfaces as a `proposal` feed card regardless (08 §5, superseding D5). Cleared by mark_ready. */
            approval_requested: boolean;
            /** @description Set iff state is blocked (03 I4); full text, shown on the card (07 §7). */
            blocked_reason?: string | null;
            /**
             * Format: date-time
             * @description Set by mark_ready; the pull's tie-breaker (03 §5).
             */
            ready_at?: string | null;
            /** Format: date-time */
            created_at: string;
            /**
             * Format: date-time
             * @description Time of the ticket's last mutation of any kind (bumped by nudges too).
             */
            updated_at: string;
            /**
             * Format: date-time
             * @description When the ticket last entered its current `state` (03 §2.2). Advances only on a real state transition, never on a same-state mutation such as a Working->Working nudge — the true "time in status" clock the client renders as the ticket-row subtext.
             */
            state_changed_at: string;
        };
        /** @description One live worker's real underlying session status, joined to its most-recent ticket binding (amended 2026-07-05). This is the actual agent/session running state — distinct from a ticket's board-column placement — so the Streams view can show a stopped or errored session instead of a hardcoded "building". worker_id is the board slot uuid; ticket_id is "" for an idle-pool worker that never ran a send. */
        AgentStatus: {
            worker_id: string;
            ticket_id: string;
            /**
             * @description building = alive with a turn in flight; idle = alive, no turn; stopped = session auto-stopped/not running; errored = terminal session failure; starting = session provisioning, not reachable yet.
             * @enum {string}
             */
            status: "building" | "idle" | "stopped" | "errored" | "starting";
        };
        /** @description GetBoard's full snapshot (03 §4), grouped in render order — the `board` SSE event payload and GET /api/board's response body are the identical shape (04 D7): absolute, never a delta, so a reconnect's resync is just "render the next board event" (07 §7–§8). `ready` is in exact pull order, top-to-bottom, so the user sees what gets pulled next (03 §5, 07 §7). */
        Board: {
            shaping: components["schemas"]["Ticket"][];
            ready: components["schemas"]["Ticket"][];
            blocked: components["schemas"]["Ticket"][];
            working: components["schemas"]["Ticket"][];
            done: components["schemas"]["Ticket"][];
            /** @description Total worker capacity slots (03 §2.3). */
            worker_total: number;
            /** @description Free (non-busy) worker slots — the capacity chip (07 §7). */
            worker_free: number;
            /** @description Live workers with their real session status, joined server-side for the Streams view (amended 2026-07-05). Absolute like the rest of the snapshot; empty before the first worker is live. Keyed to tickets by ticket_id. */
            agents: components["schemas"]["AgentStatus"][];
        };
        /** @description One persisted transcript row (07 §3), as returned oldest-first by GET /api/messages. */
        Message: {
            /** Format: int64 */
            message_id: number;
            /** @enum {string} */
            role: "user" | "kiln";
            text: string;
            /** Format: date-time */
            timestamp: string;
        };
        /** @description POST /api/message body (07 §4). Text only in v1; 09 adds STT in front of this seam. */
        MessageRequest: {
            text: string;
        };
        /** @description POST /api/message's 202 body (07 §4) — both ids the client needs to reconcile its optimistic send. */
        MessagePostResponse: {
            /** Format: int64 */
            event_id: number;
            /** Format: int64 */
            message_id: number;
        };
        /** @description The `say` SSE event payload (07 §4) — one event per brain say (renamed from `speak`, 07 A1). message_id matches the corresponding Message row from GET /api/messages/the transcript. */
        SayEvent: {
            /** Format: int64 */
            message_id: number;
            text: string;
            /** Format: date-time */
            at: string;
        };
        /** @description POST /api/voice/token's 200 body (09 §2, §6): a short-lived AssemblyAI Universal-Streaming token and its absolute expiry. The client opens the STT WebSocket with `token` and refreshes proactively before `expires_at`. */
        VoiceToken: {
            /** @description The temporary AssemblyAI streaming token (bearer for the wss connection). */
            token: string;
            /**
             * Format: date-time
             * @description Absolute expiry (backend-computed from the provider's redemption window).
             */
            expires_at: string;
        };
        /** @description One backlog item on the primary screen (08 §3). Hybrid-sourced but the client renders one list and never knows the difference: `blocker` and `proposal` are derived from board state; `update` and `preview` are brain-authored notification rows. The visible tag (Blocker/Proposal/ Update/Preview) is derived from `kind` on the client. */
        FeedCard: {
            /**
             * @description blocker -> ticket in the Blocked zone (body is blocked_reason); proposal -> Shaping ticket with approval_requested (body is the shaped summary, Accept affordance shown); update -> brain-authored note; preview -> brain-authored note with an image; poke -> mechanical stall nudge (body empty; the ticket title carries a 👉); done -> mechanical completion card (body empty; the ticket title carries a ✅).
             * @enum {string}
             */
            kind: "blocker" | "proposal" | "update" | "preview" | "poke" | "done";
            /** @description Stable render key. `blocker:<ticket_id>`, `proposal:<ticket_id>`, or `update:<notification_id>`. */
            id: string;
            /** @description The short stream/ticket label shown above the card body (e.g. the ticket title). May be empty for an authored note with no linked ticket. */
            label: string;
            body: string;
            /** @description Set for blocker/proposal (the derived ticket); optional for authored notes. */
            ticket_id?: string | null;
            /**
             * Format: int64
             * @description Set for update/preview cards; the id the client passes to /api/feed/seen as the high-water mark (08 §3).
             */
            notification_id?: number | null;
            /** @description Set for preview cards — the embedded render (08 §3, 4c). */
            image_url?: string | null;
            /**
             * Format: date-time
             * @description When the card became current (blocked-at for blockers, request time for proposals, post time for notes); drives the relative age label.
             */
            created_at: string;
        };
        /** @description Server-derived header status counts (08 §2). The client renders the one-line summary from these: "N blocker(s) · M updates" when blockers exist, the active-stream count ("K streams") when not, "Nothing active" when the feed is empty; plus the all-clear detail line (building/idle/last word). */
        FeedSummary: {
            blocker_count: number;
            /** @description Count of unseen update/preview cards. */
            update_count: number;
            /** @description Number of active ticket streams (working + blocked). */
            stream_count: number;
            /** @description Streams with a worker actively building (working). */
            building: number;
            /** @description Active streams not currently building. */
            idle: number;
            /**
             * Format: date-time
             * @description Timestamp of the most recent brain say/update, for "last word 6m ago".
             */
            last_word_at?: string | null;
            /**
             * Format: int64
             * @description The persistent seen high-water mark (08 D2′): the greatest notification id the user has acked. Update/preview cards with a greater notification_id are "new since last visit" (above the last-seen divider); those at or below it are retained history (below it). Null when nothing has ever been seen. The client freezes this at the first snapshot of a session so marking-seen-on-view doesn't move the divider mid-session.
             */
            last_seen_notification_id?: number | null;
        };
        /** @description GET /api/feed's body and the `feed` SSE event payload — the identical absolute shape (08 §3, D2′). `cards` is in strict order: unresolved blockers, then pending proposals, then updates newest-first (seen and unseen — retained history). `cards` carries only the NEWEST PAGE of updates; `has_more_history` signals older ones are pageable via /api/feed/history. */
        FeedSnapshot: {
            summary: components["schemas"]["FeedSummary"];
            cards: components["schemas"]["FeedCard"][];
            /** @description True when retained update/preview history exists older than the oldest update card in `cards` — page it in via GET /api/feed/history (08 D2′). */
            has_more_history: boolean;
        };
        /** @description One older page of retained update/preview history (GET /api/feed/history — 08 §3, D2′): notification-backed cards only, newest-first, older than the request's `before` cursor. Board-derived blocker/proposal cards are never paged. */
        FeedHistoryPage: {
            cards: components["schemas"]["FeedCard"][];
            /** @description True when another older page remains beyond this one. */
            has_more: boolean;
        };
        /** @description POST /api/feed/seen body (08 §3) — the seen high-water mark. */
        FeedSeenRequest: {
            /** Format: int64 */
            last_notification_id: number;
        };
        /** @description The `activity` SSE event payload (08 §4) — ephemeral, never stored. `thinking` brackets a brain pass (renders the spinner); `toast` confirms one side-effect board transition (renders the auto-dismissing pill). Fields are keyed by `kind`, mirroring Ticket.state's enum discriminator. */
        ActivityEvent: {
            /** @enum {string} */
            kind: "thinking" | "toast";
            /** @description For kind=thinking — true when a pass starts, false when it ends. */
            on?: boolean | null;
            /**
             * @description For kind=toast — the transition: started (dispatched), nudged (new turn sent), finished (accepted to done), queued (marked ready).
             * @enum {string|null}
             */
            verb?: "started" | "nudged" | "finished" | "queued" | null;
            /** @description For kind=toast — the affected ticket's title. */
            ticket_title?: string | null;
        };
        /** @description The signed-in user's account view (11 §4). Secret values never appear. */
        Me: {
            user: components["schemas"]["MeUser"];
            /** @description Absent until the user creates their project. */
            project?: components["schemas"]["MeProject"];
            settings: components["schemas"]["MeSettings"];
        };
        MeUser: {
            github_login: string;
            display_name: string;
            avatar_url: string;
        };
        MeProject: {
            name: string;
            repo_url: string;
            amika_snapshot: string;
            brain_model: string;
            worker_count: number;
        };
        /** @description Config status — secrets as presence+fingerprint only (11 §3 D7). */
        MeSettings: {
            anthropic_api_key: components["schemas"]["SecretStatus"];
            amika_api_key: components["schemas"]["SecretStatus"];
            github_auth_token: components["schemas"]["SecretStatus"];
            amika_claude_cred_id: string;
        };
        SecretStatus: {
            set: boolean;
            /** @description Last 4 characters of the stored secret; empty when unset. */
            tail: string;
        };
        /** @description All fields optional; empty or omitted means unchanged (write-only secrets). */
        SettingsUpdateRequest: {
            anthropic_api_key?: string;
            amika_api_key?: string;
            github_auth_token?: string;
            amika_claude_cred_id?: string;
        };
        ProjectUpdateRequest: {
            name: string;
            repo_url: string;
            amika_snapshot?: string;
            brain_model?: string;
            worker_count?: number;
        };
        VerifyCheck: {
            /** @enum {string} */
            name: "anthropic" | "amika" | "repo";
            /** @enum {string} */
            status: "ok" | "failed" | "skipped";
            message: string;
        };
        VerifyResponse: {
            checks: components["schemas"]["VerifyCheck"][];
        };
        /** @description The VAPID public key for pushManager.subscribe (02 §10). */
        PushKey: {
            /** @description Base64url-encoded VAPID application server key. */
            key: string;
        };
        /** @description The global push-notification frequency (02 §10). `blocked` — the default, preserving prior behavior — sends a push only when a ticket needs a human decision; `all` sends a push on every feed update, a testing aid for confirming push delivery. Extensible: more modes may be added later. */
        NotificationMode: {
            /**
             * @description Which feed updates fire a push notification.
             * @enum {string}
             */
            mode: "all" | "blocked";
        };
        /** @description A browser PushSubscription as produced by `PushSubscription.toJSON()` — the endpoint URL plus the p256dh and auth keys used to encrypt Web Push payloads (RFC 8291). */
        PushSubscription: {
            /** @description The push service URL messages are POSTed to. */
            endpoint: string;
            keys: {
                /** @description Base64url client public key (ECDH P-256). */
                p256dh: string;
                /** @description Base64url client auth secret. */
                auth: string;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is up. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    getBoard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current board snapshot. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Board"];
                };
            };
        };
    };
    postMessage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MessageRequest"];
            };
        };
        responses: {
            /** @description Accepted — the user row is durably appended and the human.message event is enqueued. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessagePostResponse"];
                };
            };
        };
    };
    getMessages: {
        parameters: {
            query?: {
                /** @description Maximum number of most-recent rows to return. */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The most-recent `limit` transcript rows, oldest-first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"][];
                };
            };
        };
    };
    getFeed: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current feed snapshot. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedSnapshot"];
                };
            };
        };
    };
    getFeedHistory: {
        parameters: {
            query?: {
                /** @description Exclusive upper-bound notification id; returns cards with id < before. Omit for the newest page. */
                before?: number;
                /** @description Page size (default 30, bounds 1–100). */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One older page of update/preview cards, newest-first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedHistoryPage"];
                };
            };
        };
    };
    postFeedSeen: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedSeenRequest"];
            };
        };
        responses: {
            /** @description Accepted — the seen high-water mark was stamped. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    dismissFeedCard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The card's notification id (FeedCard.notification_id). */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accepted — the card was dismissed. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    dismissAllFeedCards: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accepted — all notifications were dismissed. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    acceptTicket: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The Shaping ticket's id (must have approval_requested set). */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accepted — the acceptance user row is appended and the human.message event is enqueued for the brain. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessagePostResponse"];
                };
            };
        };
    };
    postVoiceToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A temporary streaming token and its absolute expiry. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VoiceToken"];
                };
            };
            /** @description The STT provider failed to mint a token. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getPushKey: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The VAPID public key. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PushKey"];
                };
            };
            /** @description Push is not configured on this deployment. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    postPushSubscribe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PushSubscription"];
            };
        };
        responses: {
            /** @description Subscription stored. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid request body. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getPushMode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The current mode. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationMode"];
                };
            };
        };
    };
    putPushMode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NotificationMode"];
            };
        };
        responses: {
            /** @description The mode after the update. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationMode"];
                };
            };
            /** @description Invalid request body (mode not one of the allowed values). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getStream: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description text/event-stream carrying `board` (Board), `say` (SayEvent), `feed` (FeedSnapshot), and `activity` (ActivityEvent) named SSE events. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The signed-in user's account view. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            /** @description No valid session. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    putSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsUpdateRequest"];
            };
        };
        responses: {
            /** @description Updated account view (same shape as GET /api/me). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            /** @description Invalid request body. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No valid session. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    putProject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectUpdateRequest"];
            };
        };
        responses: {
            /** @description Updated account view (same shape as GET /api/me). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            /** @description Invalid request body. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No valid session. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    postSettingsVerify: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Per-check results; unconfigured checks report status "skipped". */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerifyResponse"];
                };
            };
            /** @description No valid session. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
